name: Acceptance Test

on:
  workflow_call:

jobs:
  # Run acceptance tests in a matrix with Terraform CLI versions on merge to master
  acceptance-test:
    name: Terraform Provider Acceptance Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: provider
    timeout-minutes: 15
    concurrency: "ci"  # fixed group so that it never parallel, even in different PR
    strategy:
      fail-fast: false
      max-parallel: 1  # acceptance tests create real infra, so no parallel run is enabled
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '1.3.*'
          - '1.4.*'
          - '1.5.*'
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          go-version: '1.20'
          cache: true
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - run: cat .github-action.env >> $GITHUB_ENV  # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      - env:
          TF_ACC: "1"
          ACC_TEST_CISCO_CDO_API_TOKEN: ${{ secrets.ACC_TEST_CISCO_CDO_API_TOKEN }}
          IOS_RESOURCE_PASSWORD: ${{ secrets.IOS_RESOURCE_PASSWORD }}
          ASA_RESOURCE_SDC_PASSWORD: ${{ secrets.ASA_RESOURCE_SDC_PASSWORD }}
        run: go test -v -cover ./...
        timeout-minutes: 10