# needs module-build.yml
name: Unit Test
on:
  workflow_call:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          go-version: '1.20'
          cache: true
      - name: Run Go Test
        run: go test ./...