name: Merge

on:
  push:
    branches:
      - 'main'
env:
  AWS_REGION: "us-west-2"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/module-build.yml
    secrets: inherit

  unit-test:
    needs: build
    uses: ./.github/workflows/module-unit-test.yml
    secrets: inherit

  acceptance-test:
    needs: unit-test
    uses: ./.github/workflows/module-acceptance-test.yml
    secrets: inherit

  tag-version:
    needs: [ acceptance-test, unit-test ]
    uses: ./.github/workflow/module-tag-version.yml
    secrets: inherit

  release:
    needs: tag-version
    uses: ./.github/workflows/module-release.yml
    secrets: inherit

  scan-for-hardcoded-secrets:
    uses: ./.github/workflows/module-scan-secrets.yml
    secrets: inherit

  generate:
    uses: ./.github/workflows/module-generate.yml
    secrets: inherit






